### ISSUE TITLE
Checklist for deployment at Japan7

### ISSUE THREAD

**Issue by odrling** [Japan7/karaberus#40]
Mostly as a way to prioritise what to work on for a deployment at Japan7 since some issues are more important for basic functionality than others.
To deploy we should at least have a plan for data migration, so I'll be working on that in priority ~~but of course we want a working app eventually~~.

# Data Migration
- [x] Migration of our previous karaoke database https://github.com/odrling/karawanko 
- [x] Keeping ids of kara.moe imports somewhere: https://0x0.st/XB_G.json

# Actually useable app
- [x] kara.moe imports #34 
- [x] Logging database changes #35
- Web frontend
  - [x] Karaoke creation and upload (could be better but works)
  - [x] Karaoke browsing
  - [ ] Karaoke issues (not yet in db)
  - [x] Font library
  - [x] Tokens creation/management #55 
- [x] A sync client to download files [wankosync](https://github.com/Japan7/wankotools)
- [x] Feed a dakara server #38 
- [ ] Have a decent search function #39 
- [x] Admin users (required to start the migration which has to be done by an admin) #56

**Comment by odrling** [comment]
there's a milestone now in place of this issue https://github.com/Japan7/karaberus/milestone/1
